spring:
  application:
    name: upload-service
  cloud:
    nacos:
      # Nacos Config 配置项，对应 NacosConfigProperties 配置属性类
      config:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        namespace: 07ae1dd3-49ed-40cd-b489-1a57aa75527b # 使用的 Nacos 的命名空间，默认为 null
#        group: DEFAULT_GROUP # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
#        name: upload-service # 使用的 Nacos 配置集的 dataId，默认为 spring.application.name
        prefix: ${spring.application.name}
        file-extension: yaml # 使用的 Nacos 配置集的 dataId 的文件拓展名，同时也是 Nacos 配置集的配置格式，默认为 properties
